{{- if .Values.gcp.workloadIdentity.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gcp.workloadIdentity.kubernetesServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.workloadIdentity.gcpServiceAccount | quote }}
{{- end }}
